import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read the idioms JSON file
const idiomData = JSON.parse(fs.readFileSync(path.join(__dirname, 'public/idioms-2000.json'), 'utf8'));

// Function to generate a clunky version of an idiom
function generateClunkyVersion(idiom) {
  const clunkyVersions = {
    "A barking dog seldom bites": "A dog that barks a lot usually does not bite",
    "A bit much": "This is too many",
    "A bridge too far": "This is going to an excessive distance",
    "A chain is no stronger than its weakest link": "The strength of a chain is limited by its weak part",
    "A day late and a dollar short": "He comes one day after and with money missing",
    "A fool and his money are soon parted": "A foolish person and his money will be separated quickly",
    "A fool at 40 is a fool forever": "If you are a fool when you are 40 years old, you will be a fool always",
    "A fresh pair of eyes": "New eyes that did not see this before",
    "A hitch in your giddy-up": "Something is wrong with your movement or momentum",
    "A lick and a promise": "Doing something quickly and carelessly",
    "A light purse is a heavy curse": "Not having money creates big problems",
    "A List": "A list that is very important",
    "A little bird told me": "I heard from an unknown small source",
    "A little learning is a dangerous thing": "Having a small amount of knowledge is not safe",
    "A long row to hoe": "Much work that takes a long time to complete",
    "A lost ball in the high weeds": "Something that is very difficult to find",
    "A lot on my plate": "I have many things I must do",
    "A month of Sundays": "A very long period of time",
    "A OK": "Everything is correct and good",
    "A penny for your thoughts": "Tell me what you are thinking about",
    "A penny saved is a penny earned": "If you save money, you gain money",
    "A picture is worth a thousand words": "Showing something is better than explaining it with words",
    "A poor man's something": "Something that is like a more expensive thing but cheaper",
    "A pretty penny": "A large amount of money",
    "A problem shared is a problem halved": "If you tell someone about your problem, it becomes smaller",
    "A rising tide lifts all boats": "When conditions improve for everyone, everyone benefits",
    "A rolling stone gathers no moss": "If you keep moving, you do not accumulate things",
    "A shallow brook babbles the loudest": "People with little intelligence talk the most",
    "A slice off a cut loaf is never missed": "Taking a small part from something already cut is not noticed",
    "A steal": "Something that costs much less than it is worth",
    "A still tongue keeps a wise head": "If you do not speak, people think you are wise",
    "A textbook case": "An example that is exactly like what is written in books",
    "A watched pot never boils": "If you wait for something to happen, it seems to take longer",
    "A1": "The very best quality",
    "ABC": "The most basic and simple things",
    "Abide by a decision": "Accept and follow what was decided",
    "Abject lesson": "A teaching moment that shows something clearly",
    "About as useful as a chocolate teapot": "Something that is completely not useful at all",
    "About face": "Turn around completely and face the opposite direction",
    "Above and beyond": "More than what is required or expected",
    "Above board": "Honest and not secret",
    "Above par": "Better than average or expected",
    "Above the fold": "In the most important visible location",
    "Above the salt": "In a position of importance or honor",
    "Absence makes the heart grow fonder": "When people are apart, they like each other more",
    "Accident waiting to happen": "Something dangerous that will cause a problem soon",
    "Ace in the hole": "A hidden advantage that you will use later",
    "Ace up your sleeve": "A secret plan or advantage that you will use",
    "Achilles' heel": "A weak point in something that seems strong",
    "Acid test": "A test that will show if something is true or real",
    "Across the board": "Affecting all people or all things equally",
    "Across the ditch": "In or from the other place across a body of water",
    "Across the pond": "In or from the other country across the ocean",
    "Act of God": "Something that happens because of nature, not people",
    "Act of war": "A hostile action by one country against another",
    "Act your age, not your shoe size": "Behave like your real age, not like you are much younger",
    "Actions speak louder than words": "What you do is more important than what you say",
    "Adam's ale": "Plain water with no flavoring",
    "Adam's apple": "The part of your neck that moves when you swallow",
    "Add fuel to the fire": "Make a situation worse by doing something else bad",
    "Add insult to injury": "Do something bad to someone who is already hurt",
    "After the watershed": "After nine o'clock at night on British television",
    "After your own heart": "Someone who has the same interests and values as you",
    "Against the clock": "Try to finish something before a time deadline",
    "Against the grain": "Do something in a way that is opposite to what is normal or expected",
    "Against your better judgment": "Do something even though you know it is not a good idea",
    "Age before beauty": "Let the older person go first",
    "Agony aunt": "A person who gives advice in a newspaper or magazine",
    "Ahead of the curve": "Do something before most other people do it",
    "Ahead of the pack": "Better or faster than others",
    "Ahead of time": "Before the scheduled or expected time",
    "Air your dirty laundry in public": "Tell people about your private or shameful problems",
    "Albatross around your neck": "A big problem that you must carry with you",
    "Alike as two peas": "Very similar to each other",
    "Alive and kicking": "Still active and doing things",
    "All ages and stripes": "People of all different types and backgrounds",
    "All along": "The whole time from the beginning",
    "All and sundry": "Everyone without exception",
    "All bark and no bite": "Someone who talks tough but does not fight",
    "All bets are off": "When something unexpected happens, the agreement no longer applies",
    "All but": "Almost, nearly",
    "All cats are grey in the dark": "When you cannot see differences, all things look the same",
    "All dressed up and nowhere to go": "Prepared to do something but you cannot do it",
    "All ears": "Listening very carefully to what someone is saying",
    "All eyes on me": "Everyone is looking at me",
    "All fingers and thumbs": "Very clumsy and dropping things",
    "All hat, no cattle": "Talking big but not having much of value",
    "All heart": "Having good intentions and being kind",
    "All hell broke loose": "Everything became chaotic and out of control",
    "All in a day's work": "Something that is normal and expected for your job",
    "All in your head": "Something that you imagine but that is not real",
    "All mod cons": "All modern conveniences and comforts",
    "All mouth and trousers": "Talking a lot but not doing anything",
    "All my eye and Peggy Martin": "Lies and nonsense",
    "All of the above": "Every choice that was mentioned",
    "All over bar the shouting": "The end result is already decided, the talking is done",
    "All over Hell's half acre": "In many different places scattered around",
    "All over the map": "Going in many different directions without a plan",
    "All over the place": "In many different locations without organization",
    "All over the shop": "Scattered and disorganized in many places",
    "All over the show": "Disorganized and going in many directions",
    "All roads lead to Rome": "Many different methods will result in the same conclusion",
    "All set": "Everything is ready",
    "All sixes": "Everything is in perfect order",
    "All skin and bone": "Very thin and having no muscle",
    "All square": "Even and equal, no debt owed",
    "All talk and no trousers": "Saying things but not doing them",
    "All that glitters is not gold": "Something that looks good may not be good",
    "All the rage": "Very popular right now",
    "All the tea in China": "Everything of great value",
    "All things to all people": "Trying to please everyone by being different things to different people",
    "All work and no play makes Jack a dull boy": "If you only work and never have fun, you become dull",
    "All your eggs in one basket": "Putting all your resources into one thing that is risky",
    "All-rounder": "Someone who is good at many different things",
    "All-singing, all-dancing": "With all the modern features and capabilities",
    "All's fair in love and war": "In difficult situations, any method is acceptable",
    "All's well that ends well": "If the result is good, everything else was fine",
    "Almost only counts in horseshoes and hand grenades": "Being almost right is not good enough except in certain games",
    "Alter ego": "Another person who is very similar to you or represents you",
    "Always a bridesmaid, never a bride": "Always in a secondary role, never in the main role",
    "Ambulance chaser": "A lawyer who tries to get business from injured people",
    "Amen": "I agree completely with what was just said",
    "An apple a day keeps the doctor away": "Eating healthy food prevents sickness",
    "An Englishman's home is his castle": "Your home is your private space that you control",
    "An old flame": "A person you had a romantic relationship with in the past",
    "An ounce of prevention is worth a pound of cure": "Stopping a problem early is better than fixing it later",
    "And all that jazz": "And other similar things I could mention",
    "Angry as a bear": "Very angry",
    "Angry as a bull": "Very angry like an angry bull",
    "Answers on a postcard": "Send your answer by postcard",
    "Ants in your pants": "Being nervous and unable to sit still",
    "Any port in a storm": "When you need help, you accept it from anyone",
    "Any Tom, Dick or Harry": "Any regular person, not someone special",
    "Apple of your eye": "A person you love very much and are proud of",
    "Apple pie order": "Everything organized perfectly and neatly",
    "Apples and oranges": "Two things that are too different to compare",
    "Apples for apples": "Comparing similar things fairly",
    "Apron strings": "Dependence on your mother or parents",
    "Argue the toss": "Argue about a decision that has already been made",
    "Arm and a leg": "A very high price that costs a lot of money",
    "Armchair critic": "Someone who gives opinions without doing the work",
    "Armchair quarterback": "Someone who comments on a game without playing it",
    "Armed to the teeth": "Having lots of weapons or supplies",
    "Around the clock": "All twenty-four hours continuously",
    "Arrow in the quiver": "Another tool or weapon you can use",
    "As a rule": "Usually, in most situations",
    "As cold as ice": "Very cold",
    "As cold as stone": "Very cold like stone",
    "As cool as a cucumber": "Very calm and not worried",
    "As good as new": "In perfect condition like a new thing",
    "As mad as a hatter": "Very crazy",
    "As mad as a wrongly shot hog": "Very angry and crazy",
    "As much use as a chocolate fire-guard": "Completely useless",
    "As much use as a chocolate teapot": "Completely without usefulness",
    "As much use as a handbrake on a canoe": "Completely useless for the situation",
    "As neat as a new pin": "Very clean and organized",
    "As one man": "All together at the same time",
    "As rare as hen's teeth": "Very rare and hard to find",
    "As the actress said to the bishop": "Used to make a joke about something said",
    "As the crow flies": "In a straight line between two points",
    "As you sow, so shall you reap": "The consequences of your actions return to you",
    "Asleep at the switch": "Not paying attention when you should be",
    "Asleep at the wheel": "Not paying attention when you should be driving",
    "At a drop of a dime": "Immediately and without hesitation",
    "At a loose end": "Not having anything to do",
    "At a loss": "Not knowing what to say or do",
    "At a snail's pace": "Very slowly",
    "At a stretch": "If absolutely necessary or with difficulty",
    "At arm's length": "Keeping someone at a distance emotionally or physically",
    "At cross purposes": "Trying to do different things at the same time",
    "At daggers drawn": "In strong disagreement or conflict",
    "At death's door": "Very near to dying",
    "At each other's throats": "Fighting and arguing intensely",
    "At full tilt": "Moving with great speed and force",
    "At gunpoint": "Threatened with a gun",
    "At large": "Not caught and still free",
    "At loggerheads": "Disagreeing completely",
    "At loose ends": "Not having anything to do",
    "At odds": "Disagreeing about something",
    "At sea": "Not knowing what is happening, confused",
    "At the bottom of the totem pole": "In the least important position",
    "At the coalface": "In the location where the real work happens",
    "At the crossroads": "At a point where you must make an important decision",
    "At the drop of a hat": "Immediately, without needing to be asked again",
    "At the end of the day": "After everything is considered",
    "At the end of your rope": "Having patience that is completely used up",
    "At the end of your tether": "Having patience that is completely used up",
    "At the fore": "In the front, in the most important position",
    "At the top of my lungs": "Speaking or shouting very loudly",
    "At the top of the list": "The most important item on the list",
    "At the top of your lungs": "Shouting very loudly",
    "At the top of your voice": "Speaking very loudly",
    "At your fingertips": "Available and ready to use whenever you need it",
    "At your wits' end": "Very confused and not knowing what to do",
    "Average Joe": "An ordinary person with no special qualities",
    "Avowed intent": "A stated purpose that you openly declare",
    "Away with the fairies": "Not paying attention, in your own imagination",
    "Awe inspiring": "Causing amazement and respect",
    "AWOL": "Absent without permission or without saying where you are",
    "Axe to grind": "Having a reason to be upset about something",
    "Babe in arms": "A baby being held in someone's arms",
    "Babe in the woods": "An inexperienced person in a new situation",
    "Baby boomer": "A person born after World War II",
    "Back burner": "Not important right now, put aside for later",
    "Back foot": "In a defensive position",
    "Back number": "No longer important or modern",
    "Back the wrong horse": "Support someone or something that will lose",
    "Back to back": "Following immediately after one another",
    "Back to square one": "Return to the beginning to start over",
    "Back to the drawing board": "Start again with a new plan",
    "Back to the salt mines": "Return to work, usually unpleasant work",
    "Back to the wall": "In a difficult position with few options",
    "Back-handed compliment": "A compliment that is actually an insult",
    "Back-of-the-envelope calculation": "A quick rough calculation without precision",
    "Backseat driver": "Someone who gives unwanted advice while you do something",
    "Bad Apple": "One person who spoils the group",
    "Bad blood": "Anger and lack of trust between people",
    "Bad egg": "A bad person who cannot be trusted",
    "Bad hair day": "A day when everything goes wrong",
    "Bad mouth": "Talk badly about someone",
    "Bad shape": "In poor condition",
    "Bad taste in your mouth": "A negative feeling about something",
    "Bad workers always blame their tools": "Incompetent people make excuses",
    "Bag and baggage": "Everything you own, completely",
    "Bag of bones": "A very thin person with visible bones",
    "Bag of nerves": "Someone who is very nervous",
    "Baker's dozen": "Thirteen instead of twelve",
    "Bald as a coot": "Completely without hair",
    "Ball is in your court": "It is your turn to take action",
    "Balloon goes up": "When something happens, the action begins",
    "Ballpark figure": "An approximate number that may not be exact",
    "Balls to the walls": "Going as fast and as hard as possible",
    "Banana republic": "A small country with an unstable government",
    "Banana skin": "A situation that causes embarrassment",
    "Band-Aid on a bullet wound": "A small solution to a big problem",
    "Bandit territory": "An area controlled by criminals",
    "Baptism of fire": "A very difficult first experience",
    "Bar fly": "Someone who spends lots of time in bars",
    "Bare your heart": "Tell someone about your true feelings",
    "Barefaced liar": "Someone who lies without being ashamed",
    "Bark is worse than their bite": "Someone seems more dangerous than they are",
    "Barking up the wrong tree": "Looking in the wrong place for something",
    "Barkus is willing": "The couple is willing to get married",
    "Barrack-room lawyer": "Someone who gives legal advice but is not a lawyer",
    "Barrel of laughs": "A very funny thing or person",
    "Basket case": "Someone who is very confused or mentally unstable",
    "Bat an eyelid": "Show any emotional reaction or surprise",
    "Bated breath": "Waiting with excitement and nervousness",
    "Bats in the belfry": "Crazy, not thinking correctly",
    "Batten down the hatches": "Prepare for something difficult to happen",
    "Batting a thousand": "Doing very well, succeeding at everything",
    "Battle of nerves": "Trying to remain calm while nervous",
    "Be all ears": "Listen carefully and with full attention",
    "Be careful what you wish for": "Your wish might cause problems if it comes true",
    "Be on the pig's back": "Be in a very good situation",
    "Be out in force": "Appear in large numbers",
    "Be out in left field": "Have strange or unusual ideas",
    "Be that as it may": "Although that may be true, other things matter more",
    "Be true blue": "Be completely loyal and dependable",
    "Be up the spout": "Be ruined or destroyed",
    "Beam me up, Scotty": "Make this situation stop, get me out of here",
    "Bean counter": "An accountant or financial person",
    "Bear fruit": "Produce good results from your efforts",
    "Bear market": "When stock prices are falling",
    "Bear the brunt": "Handle the main force or effect of something negative",
    "Beard the lion in his own den": "Challenge a powerful person in their own space",
    "Beat about the bush": "Talk around a subject without saying the main point",
    "Beat someone to the draw": "Do something before someone else does it",
    "Beat swords into ploughshares": "Convert weapons into tools for peaceful use",
    "Beat the daylights out of someone": "Hit someone very hard",
    "Beat the rap": "Escape punishment for something",
    "Beat the tar out of": "Hit someone very hard",
    "Beat them at their own game": "Defeat someone using their own methods",
    "Beat to the punch": "Do something before someone else does it",
    "Beat your brains out": "Work very hard thinking about something",
    "Beating a dead horse": "Continuing to discuss something that is already settled",
    "Beauty is in the eye of the beholder": "Different people find different things beautiful",
    "Beauty is only skin deep": "Looking good is not the most important quality",
    "Beck and call": "Always available to do what someone wants",
    "Bedroom eyes": "A romantic look that shows attraction",
    "Bee in your bonnet": "An idea that you keep thinking about",
    "Bee's Knees": "Something that is very good and modern",
    "Beeline for": "Go directly toward something very quickly",
    "Been around the block a few times": "Have lots of experience",
    "Been in the wars": "Have had difficult times or injuries",
    "Been there, done that": "Have experienced something before",
    "Beer and skittles": "Fun and games with no work",
    "Before the ink is dry": "Before the agreement is even finalized",
    "Before you can say Jack Robinson": "Very quickly",
    "Before you can say knife": "Very quickly",
    "Beg the question": "Ask a question that assumes the answer",
    "Beggars can't be choosers": "When you need help, you cannot be particular about what you get",
    "Behind bars": "In prison",
    "Behind closed doors": "In private, not in public",
    "Behind someone's back": "Without someone knowing, in secret",
    "Behind the curve": "Not as advanced or current as others",
    "Behind the eight ball": "In a difficult position",
    "Behind the times": "Not modern or current",
    "Believe in the hereafter": "Understand where the person went after they died",
    "Believe you me": "I am telling you the truth",
    "Bell the cat": "Do something dangerous that nobody else will do",
    "Bells and whistles": "Extra features that are not necessary",
    "Bells on": "Enthusiastically, with lots of energy",
    "Belly up": "Come up to the counter or bar to stand in front",
    "Below par": "Not as good as expected or average",
    "Below the belt": "Attack someone in a way that is unfair or cruel",
    "Below the fold": "In an unimportant location that is not seen at first",
    "Below the salt": "In a position of less importance or honor",
    "Belt and braces": "Using two methods to make sure something happens",
    "Belt and suspenders": "Using two methods to make sure something happens",
    "Bend over backwards": "Try very hard to help or please someone",
    "Bend someone's ear": "Talk to someone for a long time about something",
    "Benjamin of the family": "The youngest person in the family",
    "Bent as a nine bob note": "Crazy or strange",
    "Beside the point": "Not the most important thing to talk about",
    "Beside themselves": "Very upset or out of control",
    "Beside yourself": "Very upset or out of control",
    "Best of a bad bunch": "The least bad choice from bad options",
    "Best of both worlds": "The advantages of two different things together",
    "Best thing since sliced bread": "An invention or idea that is very good",
    "Bet the farm": "Risk everything on one thing",
    "Bet the ranch": "Risk everything on one thing",
    "Bet your bottom dollar": "Be very sure about something",
    "Better be the head of a dog than the tail of a lion": "Better to be a leader of small things than a follower of great things",
    "Better half": "Your wife or husband",
    "Better late than never": "It is good that something happened even if it is late",
    "Better safe than sorry": "It is better to be careful to avoid problems",
    "Better than a kick in the teeth": "Better than no help at all",
    "Better than a stick in the eye": "Better than something very bad",
    "Better the devil you know": "It is safer to deal with a bad situation you understand than an unknown one",
    "Between a rock and a hard place": "Stuck with two bad choices",
    "Between the devil and the deep blue sea": "Stuck between two bad choices",
    "Between you and me and the cat's whiskers": "A secret that only we know",
    "Beyond a shadow of a doubt": "Absolutely certain",
    "Beyond belief": "Too amazing to believe",
    "Beyond our ken": "Beyond what we can understand",
    "Beyond the black stump": "Very far away in the middle of nowhere",
    "Beyond the pale": "Outside the limits of what is acceptable",
    "Big Apple": "New York City",
    "Big bucks": "A large amount of money",
    "Big cheese": "An important person",
    "Big Easy": "New Orleans",
    "Big fish": "An important person",
    "Big fish in a small pond": "Important in a small group but not bigger",
    "Big girl's blouse": "A man who is weak or sensitive",
    "Big hitter": "An important or powerful person",
    "Big nose": "Someone who is nosy and asks too many questions",
    "Big picture": "The main overall situation",
    "Big time": "Doing something on a large scale or importantly",
    "Bigger fish to fry": "More important things to do",
    "Billy Wind": "An unimportant or low-ranking person",
    "Bird in the hand is worth two in the bush": "Having something certain is better than hoping for more",
    "Bird-brain": "A stupid person",
    "Bird-dog": "Follow someone closely or watch them carefully",
    "Bird's eye view": "A view from above or a general overview",
    "Birds and the bees": "Information about reproduction and sex",
    "Birds of a feather flock together": "Similar people like to be together",
    "Birthday suit": "Naked, without clothes",
    "Bit between your teeth": "You are determined to do something",
    "Bit part": "A small role in a play or movie",
    "Bit player": "Someone with a small role or limited influence",
    "Bite off more than you can chew": "Try to do more than you are able to do",
    "Bite someone's head off": "Respond to someone with anger and harshness",
    "Bite the bullet": "Accept something painful or difficult that must be done",
    "Bite the dust": "Die or stop working",
    "Bite your lip": "Control your emotions, do not speak",
    "Bite your tongue": "Stop yourself from saying something",
    "Bits and bobs": "Small pieces and parts, miscellaneous items",
    "Bitter end": "The unpleasant final conclusion",
    "Bitter pill to swallow": "Something difficult to accept",
    "Black and blue": "Covered with bruises from being hit",
    "Black and white": "Very clear with no in-between",
    "Black as Newgate's knocker": "Completely black",
    "Black hole": "Something that takes in everything and nothing comes back out",
    "Black sheep": "The person who is not like the rest of the family",
    "Black will take no other hue": "A black person will not change their race",
    "Blackball": "Vote against someone joining a group",
    "Blank cheque": "Complete freedom to do what you want",
    "Blank slate": "Something with no history or previous information",
    "Bleed dry": "Take all someone's money",
    "Bleeding edge": "The most advanced and new technology",
    "Bleeding heart": "Someone who has too much sympathy",
    "Bless your pointy little head": "You are not very intelligent",
    "Blessing in disguise": "Something bad that turns out to be good",
    "Blind acceptance": "Accepting something without questioning it",
    "Blind as a bat": "Not able to see well",
    "Blind leading the blind": "Ignorant people trying to teach other ignorant people",
    "Blind-sided": "Surprised by something you did not see coming",
    "Blink of an eye": "A very short period of time",
    "Blood and thunder": "Loud and exciting, perhaps too much",
    "Blood from a turnip": "Trying to get something from someone who has nothing",
    "Blood is thicker than water": "Family relationships are more important than others",
    "Blood is worth bottling": "You are a very good person",
    "Blood out of a stone": "Getting something from someone who does not want to give it",
    "Blood, sweat and tears": "Hard work and suffering",
    "Blot your copybook": "Do something that damages your reputation",
    "Blow a fuse": "Become very angry",
    "Blow a gasket": "Become very angry",
    "Blow by blow": "A detailed description of each step",
    "Blow hot and cold": "Keep changing your opinion",
    "Blow me down": "I am surprised",
    "Blow off steam": "Let out angry feelings",
    "Blow out of proportion": "Make something seem bigger or more important than it is",
    "Blow out of the water": "Defeat someone completely",
    "Blow smoke": "Tell lies and pretend to be telling the truth",
    "Blow the cobwebs away": "Get fresh air and exercise",
    "Blow the whistle": "Tell authorities about illegal or wrong activity",
    "Blow your mind": "Surprise you greatly or impress you very much",
    "Blow your own horn": "Tell people how good you are",
    "Blow your own trumpet": "Tell people how good you are",
    "Blow your stack": "Become very angry",
    "Blow your top": "Become very angry",
    "Blue blood": "Aristocratic family from a long time ago",
    "Blue skies": "Happy and hopeful feelings about the future",
    "Blue-eyed boy": "Someone's favorite person who gets special treatment",
    "Bluestocking": "An intelligent woman who reads and studies a lot",
    "Boardinghouse reach": "Reaching across people to get food at the table",
    "Bob's your uncle": "That is all there is to it, it is easy",
    "Body politic": "The people and government of a state or nation",
    "Boil the ocean": "Try to do something that is impossible",
    "Boil to the surface": "Become obvious and revealed",
    "Bold as brass": "Very brave and not shy",
    "Bolt from the blue": "Something unexpected happens suddenly",
    "Bone of contention": "A point that people keep arguing about",
    "Bone to pick": "Something that you want to discuss in an angry way",
    "Boot is on the other foot": "The situation is now opposite from before",
    "Born on the wrong side of the blanket": "Born to parents who were not married",
    "Born on the wrong side of the tracks": "Born into a poor family in a bad area",
    "Born to the purple": "Born into a royal or noble family",
    "Born with a silver spoon in your mouth": "Born into a rich family",
    "Both ends meet": "Have enough money to pay your living expenses",
    "Bottom line": "The most important point",
    "Bottoms-up": "Drink everything in your glass"
  };

  if (clunkyVersions[idiom]) {
    return clunkyVersions[idiom];
  }

  // Fallback: Generate a generic clunky version if not in dictionary
  return generateGenericClunky(idiom);
}

function generateGenericClunky(idiom) {
  // Generic transformation rules for idioms not in the dictionary
  const words = idiom.split(' ');
  
  // Simple heuristics to make it sound more literal/clunky
  if (idiom.length > 30) {
    return idiom.split(' and ')[0] + ' in a very direct way';
  }
  if (idiom.includes('is')) {
    return "The fact that " + idiom;
  }
  if (words.length <= 3) {
    return "This means " + idiom;
  }
  
  return "It refers to " + idiom;
}

// Transform all idioms
const transformedData = idiomData.map(item => ({
  clunky: generateClunkyVersion(item.idiom),
  native: item.idiom
}));

// Write the output file
fs.writeFileSync(
  path.join(__dirname, 'public/idioms-clunky-native.json'),
  JSON.stringify(transformedData, null, 2),
  'utf8'
);

console.log(`Successfully transformed ${transformedData.length} idioms!`);
console.log('Output saved to: public/idioms-clunky-native.json');
